#!/bin/bash
# Update & install Java + unzip + wget
apt-get update && apt-get install -y openjdk-11-jdk wget unzip

# Download and install IJava kernel
wget https://github.com/SpencerPark/IJava/releases/download/v1.3.0/ijava-1.3.0.zip
unzip ijava-1.3.0.zip -d /tmp/ijava
/tmp/ijava/install.sh --sys-prefix
rm -rf /tmp/ijava ijava-1.3.0.zip

# Debug info (optional, can help you check logs)
java -version
jupyter kernelspec list
#!/bin/bash
apt-get update && apt-get install -y openjdk-11-jdk wget unzip
wget https://github.com/SpencerPark/IJava/releases/download/v1.3.0/ijava-1.3.0.zip
unzip ijava-1.3.0.zip -d /tmp/ijava
/tmp/ijava/install.sh --sys-prefix
rm -rf /tmp/ijava ijava-1.3.0.zip


